Update hehe

diff --git a/hehe b/hehe
--- a/hehe
+++ b/hehe
@@ -1,6 +1,6 @@
+
 #!/bin/bash
 clear
-
 # Function to display a progress bar
 fun_bar() {
     comando[0]="$1"
@@ -47,42 +47,48 @@ verif_key() {
 # Define ip_address as a global variable
 ip_address=$(hostname -I | awk '{print $1}')
 
-# Function to prompt user for verification code
-send_code_telegram() {
-    local current_time=$(date +%s)
-    local storage_file="/root/vcheck/.storage.txt"  # Hidden file with a dot prefix
-
-    # Check if the vcheck folder exists, if not create it
-    if [[ ! -d "/root/vcheck" ]]; then
-        mkdir -p /root/vcheck
-    fi
-
-    # Generate random 6-digit code
+# Function to generate and display verification code
+generate_verification_code() {
     local random_code=$(shuf -i 100000-999999 -n 1)
-
-    # Prompt user to enter the verification code
-    echo -e "\033[1;36m======================================================================================\033[0m"
-    echo -e "\033[1;31m  Verification Code: $random_code \033[0m"
-    echo -e "\033[1;36m======================================================================================\033[0m"
+    echo -e "\033[1;36m=============================================================\033[0m"
+    echo -e "\033[1;31m    VERIFICATION CODE: $random_code\033[0m"
+    echo -e "\033[1;36m=============================================================\033[0m"
     echo ""
-    echo -e "\033[1;31m  Please enter the verification code to continue: \033[0m"
-    read user_code
-
-    # Check if the entered code matches the generated code
-    if [[ "$user_code" != "$random_code" ]]; then
-        echo ""
-        echo -e "\033[1;35mInvalid code. Installation aborted.\033[0m"
-        echo ""
-        exit 1
-    else
-        # Store the code along with the IP address and timestamp
-        echo "$ip_address $random_code $current_time" > "$storage_file"
-        echo ""
-        echo -e "\033[1;32mVerification successful! Proceeding with installation...\033[0m"
-        echo ""
-        sleep 2
-    fi
+    echo -e "\033[1;33mCopy and use the verification code during installation.\033[0m"
+    echo ""
+    echo -e "\033[1;36m=============================================================\033[0m"
 }
+
+clear
+
+# Check for root privilege
+[[ "$(whoami)" != "root" ]] && {
+    echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33m◇ YOU NEED TO RUN AS ROOT!\033[0m"
+    exit 0
+}
+
+# Generate and display the verification code
+generate_verification_code
+
+# Prompt the user to enter the verification code
+echo -n -e "\033[1;33m  ENTER VERIFICATION CODE: \033[0m"
+read user_code
+last_sent=$(awk -v ip="$ip_address" '$1 == ip {print $2}' "/root/vcheck/.storage.txt")
+
+# Compare the entered code with the generated code
+if [[ -z "$user_code" || "$user_code" != "$last_sent" ]]; then
+    echo ""
+    echo -e "\033[1;35mInvalid code. Installation aborted.\033[0m"
+    echo ""
+    exit 1
+else
+    rm -rf /root/vcheck
+fi
+
+# Variable Initialization
+_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev)
+_Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig')
+_1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
 
 # Welcome message
 echo -e "\033[1;31m\033[0m"
@@ -120,12 +126,12 @@ if [[ "$add_domain" == "Y" || "$add_domain" == "y" ]]; then
         echo ""
         echo -ne "\033[1;36m◇ Please enter your domain name (e.g., example.com): \033[0m"
         read domain_name
-        echo ""
+  echo ""
         # Validate domain name format
         if [[ $domain_name =~ ^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
             # Display domain name for confirmation
-            echo -e "\033[1;33mYou entered the domain name: \033[1;32m$domain_name\033[0m"
-            echo "$domain_name" > /etc/.domain   
+            echo -e "\033[1;33mYou entered the domain name: \033[1;32m$domain_name\033[0m"      
+echo "$domain_name" > /etc/.domain   
             break
         else
             ((domain_attempts++))
@@ -155,19 +161,27 @@ wget https://iplogger.org/2lHZ43 > /dev/null 2>&1
 rm 2lHZ43 > /dev/null 2>&1
 
 # Prompt to keep or create user database
-echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+echo -e "\n\033[1;32m◇ KEY VALID!\033[1;32m"
+sleep 1s
 echo ""
-echo -e "                 \033[1;33m• \033[1;31m◇ ATTENTION!\033[1;33m• \033[0m"
-echo ""
-echo -e "\033[1;33mA User Database \033[1;32m(usuarios.db) \033[1;33mwas"
-echo -e "Found! Want to keep it by preserving the limit"
-echo -e "of Simutanea connections of users ? Or Want"
-echo -e "create a new database?\033[0m"
-echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mKeep Database Current\033[0m"
-echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCreate a New Database\033[0m"
-echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
-echo ""
-tput setaf 2 ; tput bold ; read -p "Option ?: " -e -i 1 optiondb ; tput sgr0
+[[ -f "$HOME/usuarios.db" ]] && {
+    clear
+    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+    echo ""
+    echo -e "                 \033[1;33m• \033[1;31m◇ ATTENTION!\033[1;33m• \033[0m"
+    echo ""
+    echo -e "\033[1;33mA User Database \033[1;32m(usuarios.db) \033[1;33mwas"
+    echo -e "Found! Want to keep it by preserving the limit"
+    echo -e "of Simutanea connections of users ? Or Want"
+    echo -e "create a new database?\033[0m"
+    echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mKeep Database Current\033[0m"
+    echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCreate a New Database\033[0m"
+    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+    echo ""
+    tput setaf 2 ; tput bold ; read -p "Option ?: " -e -i 1 optiondb ; tput sgr0
+} || {
+    awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
+}
 [[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
 clear
 tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "◇ WAIT FOR INSTALLATION." ; tput sgr0
@@ -217,28 +231,34 @@ inst_pct() {
 }
 
 fun_bar 'inst_pct'
-[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
+[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8080/tcp ; ufw allow 8799/tcp ; ufw allow 722/tcp ; ufw allow 81/tcp ; ufw allow 443/udp > /dev/null 2>&1 ; ufw allow 1194/udp > /dev/null 2>&1 ; ufw allow 7200/tcp > /dev/null 2>&1 ; ufw allow 7300/tcp > /dev/null 2>&1 ; ufw allow 1921/tcp > /dev/null 2>&1 ; ufw allow 8899 > /dev/null 2>&1 ; ufw allow 1207 > /dev/null 2>&1 ; ufw allow 55000:56999/tcp > /dev/null 2>&1 ; ufw allow 55000:56999/udp > /dev/null 2>&1 ; ufw --force enable > /dev/null 2>&1
+echo ""
+echo -e "\033[1;32m◇ PACKAGES INSTALLED SUCCESSFULLY!\033[0m"
+sleep 3s
+echo ""
+echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ FINALIZING INSTALLATION\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo ""
+echo -e "\033[1;33m◇ INSTALLATION IS COMPLETE IN A FEW MOMENTS!\033[0m"
+sleep 2s
 clear
+# End of installation message
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "◇ INSTALLATION COMPLETE!" ; tput sgr0
 echo ""
-echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ FINISHING...\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
 echo ""
-echo -e "      \033[1;33m◇ COMPLETING FUNCTIONS AND SETTINGS!\033[0m"
+echo -e "\033[1;32m◇  Now your VPS is ready to be used.\033[0m"
 echo ""
-fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
-clear
+echo -e "\033[1;33m◇  To access the menu, type \033[1;37m\033[44mmenu\033[0m \033[1;33mand press Enter.\033[0m"
 echo ""
-cd $HOME
-IP=$(wget -qO- ipv4.icanhazip.com)
-echo -e "        \033[1;33m  \033[1;32m◇ INSTALLATION COMPLETED.◇\033[1;33m  \033[0m"
+echo -e "\033[1;31m◇───────────────────────────────────────────────────◇\033[0m"
 echo ""
-echo -e "\033[1;31m\033[1;33m◇ MAIN COMMAND:- \033[1;32mmenu\033[0m"
-echo -e "\033[1;33m◇ MORE INFORMATION \033[1;31m(\033[1;36m◇ TELEGRAM\033[1;31m): \033[1;37m@MAPTECHVPS_MANAGER\033[0m"
-echo -e "\033[1;33m◇ SERVER IP : \033[1;37m$IP"
+echo -e "  \033[1;32m• \033[1;33mNow your SSH port is \033[1;32m22\033[1;33m.\033[0m"
 echo ""
-echo -e "    \033[1;33m◇\033[1;31m     ⏩ Don't forget to follow ⏪     \033[1;33m◇\033[0m"
+echo -e "  \033[1;32m• \033[1;33mYour \033[1;32mroot \033[1;33musername is \033[1;32mlxd1 \033[1;33mand the password is \033[1;32m0001\033[0m."
 echo ""
-echo -e "\033[1;33m◇───\033[1;31m THE WHOLE TEAM MAPTECH VPS MANAGER \033[1;33m───◇\033[0m"
+echo -e "\033[1;31m◇───────────────────────────────────────────────────◇\033[0m"
 echo ""
-sleep 2
-# Call the function to prompt user for verification code
-send_code_telegram
+echo ""
+echo -e "    \033[1;33m• \033[1;32mEASY INTERFACE FOR BEGINNERS.\033[0m"
+echo ""
+echo -e "\033[1;33m◇──────────────ㅤ🌍 MAPTECH VPS MANAGER 🌍ㅤ──────────────◇\033[0m"
+echo ""
